<a href="https://colab.research.google.com/github/Jacobian04/Deep-Learning-with-Python/blob/main/Zero-to-Mastery-Learn-PyTorch-for%20Deep-Learning/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

|Topic|Contents|
|-|-|
|Introduction|Tensor are the basic building block of all of machine learning and deep learning.|


In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


## Introduction to tensors

Tensors are the fuddamental building block of machine learning.

Their job is to represent data in a numerical way.

Image rensor shape: `[3, 224, 244]` which mean `[colour_channels, height, width]`, as in the image has `3` colour channels (redm green, blue), a height of 224 pixels and a width of 224 pixels.

![Image](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

How to create a `tensor`?

In [2]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [3]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [4]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

If you notice at outputs `torch.Size([1, 3, 3])`

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

![Image](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

| Name   | What is it? | Number of dimensions | Lower or upper (usually/example) |
|--------|-------------|----------------------|----------------------------------|
| Scalar | A single number | 0 | Lower (a) |
| Vector | A number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (y) |
| Matrix | A 2-dimensional array of numbers | 2 | Upper (Q) |
| Tensor | An n-dimensional array of numbers (can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector) | Any number | Upper (X) |


![Image](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors

A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

As a data scientist,
1. Define how machine learning model starts (initialization) 
2. Look at data (representaion) 
3. Update (optimization) its random numbers


In [5]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.8744, 0.4393, 0.8146, 0.5114],
         [0.8554, 0.5395, 0.9400, 0.1999],
         [0.1748, 0.8017, 0.0554, 0.2683]]),
 torch.float32)

We can adjust the `size` to be whatever we want.

Let's crate random tensor int the common image shape of [`224, 224, 3`] ([`height, width, color_channels`]).

In [6]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand( size=(224, 224, 3) )
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones
Sometimes you'll just want to fill tensors with zeros or ones.

> This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [7]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [8]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

Sometime, we might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

In [9]:
# Create  a range of value 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

If you want one tensor of a centain type with the same shape as another tensor.
>For example, a tensor of all zeros with the same shape as a previous tensor.

* torch.zeros_like(input)
* torch.ones_like(input)

In [10]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have some shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])